/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as EraAheadRouteImport } from './routes/era-ahead'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as GatheringsRouteImport } from './routes/gatherings'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IntentRouteImport } from './routes/intent'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SuggestRouteImport } from './routes/suggest'
import { Route as TogetherRouteImport } from './routes/together'
import { Route as TrackRouteImport } from './routes/track'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const EraAheadRoute = EraAheadRouteImport.update({
  id: '/era-ahead',
  path: '/era-ahead',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const GatheringsRoute = GatheringsRouteImport.update({
  id: '/gatherings',
  path: '/gatherings',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IntentRoute = IntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestRoute = SuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const TogetherRoute = TogetherRouteImport.update({
  id: '/together',
  path: '/together',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/chapters': typeof ChaptersRoute
  '/early-access': typeof EarlyAccessRoute
  '/era-ahead': typeof EraAheadRoute
  '/focus': typeof FocusRoute
  '/gatherings': typeof GatheringsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intent': typeof IntentRoute
  '/meet': typeof MeetRoute
  '/return': typeof ReturnRoute
  '/safety': typeof SafetyRoute
  '/suggest': typeof SuggestRoute
  '/together': typeof TogetherRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/chapters': typeof ChaptersRoute
  '/early-access': typeof EarlyAccessRoute
  '/era-ahead': typeof EraAheadRoute
  '/focus': typeof FocusRoute
  '/gatherings': typeof GatheringsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intent': typeof IntentRoute
  '/meet': typeof MeetRoute
  '/return': typeof ReturnRoute
  '/safety': typeof SafetyRoute
  '/suggest': typeof SuggestRoute
  '/together': typeof TogetherRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/chapters': typeof ChaptersRoute
  '/early-access': typeof EarlyAccessRoute
  '/era-ahead': typeof EraAheadRoute
  '/focus': typeof FocusRoute
  '/gatherings': typeof GatheringsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intent': typeof IntentRoute
  '/meet': typeof MeetRoute
  '/return': typeof ReturnRoute
  '/safety': typeof SafetyRoute
  '/suggest': typeof SuggestRoute
  '/together': typeof TogetherRoute
  '/track': typeof TrackRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/chapters'
    | '/early-access'
    | '/era-ahead'
    | '/focus'
    | '/gatherings'
    | '/how-it-works'
    | '/intent'
    | '/meet'
    | '/return'
    | '/safety'
    | '/suggest'
    | '/together'
    | '/track'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/chapters'
    | '/early-access'
    | '/era-ahead'
    | '/focus'
    | '/gatherings'
    | '/how-it-works'
    | '/intent'
    | '/meet'
    | '/return'
    | '/safety'
    | '/suggest'
    | '/together'
    | '/track'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/chapters'
    | '/early-access'
    | '/era-ahead'
    | '/focus'
    | '/gatherings'
    | '/how-it-works'
    | '/intent'
    | '/meet'
    | '/return'
    | '/safety'
    | '/suggest'
    | '/together'
    | '/track'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  ChaptersRoute: typeof ChaptersRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  EraAheadRoute: typeof EraAheadRoute
  FocusRoute: typeof FocusRoute
  GatheringsRoute: typeof GatheringsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntentRoute: typeof IntentRoute
  MeetRoute: typeof MeetRoute
  ReturnRoute: typeof ReturnRoute
  SafetyRoute: typeof SafetyRoute
  SuggestRoute: typeof SuggestRoute
  TogetherRoute: typeof TogetherRoute
  TrackRoute: typeof TrackRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/era-ahead': {
      id: '/era-ahead'
      path: '/era-ahead'
      fullPath: '/era-ahead'
      preLoaderRoute: typeof EraAheadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatherings': {
      id: '/gatherings'
      path: '/gatherings'
      fullPath: '/gatherings'
      preLoaderRoute: typeof GatheringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intent': {
      id: '/intent'
      path: '/intent'
      fullPath: '/intent'
      preLoaderRoute: typeof IntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggest': {
      id: '/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof SuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/together': {
      id: '/together'
      path: '/together'
      fullPath: '/together'
      preLoaderRoute: typeof TogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  ChaptersRoute: ChaptersRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  EraAheadRoute: EraAheadRoute,
  FocusRoute: FocusRoute,
  GatheringsRoute: GatheringsRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntentRoute: IntentRoute,
  MeetRoute: MeetRoute,
  ReturnRoute: ReturnRoute,
  SafetyRoute: SafetyRoute,
  SuggestRoute: SuggestRoute,
  TogetherRoute: TogetherRoute,
  TrackRoute: TrackRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
