import Link from "next/link";

const promises = [
  { label: "What Era is not", title: "Not a matrimony marketplace", body: "Era is not a wedding marketplace in disguise. Aynera remains a relationship-journey brand: depth first, without forcing family, caste, or wedding funnels into the pilot." },
  { label: "What may grow", title: "Future chapters are earned", body: "Shared milestones, deeper couple tools, and optional life-stage support may come later—only after the core path from Meet to Focus to Together is trusted and loved." },
  { label: "Who shapes it", title: <>Built with the<br />cohort</>, body: "Early members in Delhi, Mumbai, and Bangalore help decide what comes after just us. We listen before expanding: ambition without rushing the foundation." },
  { label: "The long promise", title: "The era of togetherness", body: "Help two people find each other with care, then help them stay—in a product that knows when to stop selling options and begin protecting a bond." },
] as const;

export function EraOverview() {
  return <main id="main" className="pd-meet-new era-overview">
    <header className="pd-meet-new-hero"><div className="shell-x pd-meet-new-hero-grid"><div className="pd-meet-new-hero-copy"><p className="pd-eyebrow"><span className="pd-accent-rule" aria-hidden />Era</p><h1 className="pd-mega">What comes after just us.</h1><p>Aynera begins with dating done differently. The era ahead is everything that can grow after two people choose each other—designed slowly, with the people living it.</p><a href="#inside-era" className="pd-meet-new-jump">Look toward the era ahead <span aria-hidden>↓</span></a></div><div className="pd-meet-new-collage era-overview-collage" aria-label="Looking toward a shared future"><figure className="pd-meet-new-photo pd-meet-new-photo-duo"><img src="/media/elaris-era-ahead-gallery.png" alt="A couple looking toward a shared horizon" width="1200" height="900" /></figure><figure className="pd-meet-new-photo pd-meet-new-photo-squad"><img src="/media/elaris-couple-space-gallery.png" alt="A couple reflecting on plans together at home" width="1536" height="1024" /></figure></div></div></header>

    <section id="inside-era" className="era-inside" aria-labelledby="era-title"><div className="shell-x"><div className="era-inside-head"><p className="pd-eyebrow"><span className="pd-accent-rule" aria-hidden />Inside this chapter</p><h2 id="era-title" className="pd-display">The horizon stays open.<br />The foundation comes first.</h2><p>Era is a direction, not a rushed feature list. Each future chapter must earn its place by helping a real relationship feel better supported.</p></div><div className="era-horizon"><span className="era-sun" aria-hidden><i>AYNERA</i></span><div className="era-horizon-promises">{promises.map(item => <article key={item.label}><p>{item.label}</p><h3 className="pd-display">{item.title}</h3><p>{item.body}</p></article>)}</div></div></div></section>

    <section className="pd-meet-new-common era-overview-close"><div className="shell-x"><div className="pd-meet-new-common-head"><p className="pd-eyebrow">The era ahead</p><h2 className="pd-display">Grow slowly.<br />Protect what matters.</h2></div><div className="pd-meet-new-principles"><article><h3>Relationships first</h3><p>Every future tool should serve people, not prolong product usage.</p></article><article><h3>Earned expansion</h3><p>New chapters arrive only after the foundation has earned trust.</p></article><article><h3>Built together</h3><p>The founding cohort helps decide what meaningful support looks like.</p></article></div><div className="pd-meet-new-common-actions"><Link href="/early-access">Join the founding circle <span aria-hidden>→</span></Link><Link href="/chapters">Back to Chapters</Link></div></div></section>
  </main>;
}
