import Link from "next/link";

const steps = [
  { phase: "Join a local network", title: "Start where there are enough people nearby.", body: "Choose the founding market, share what you are open to, and join when there is enough relevant local activity. Delhi is opening first. Mumbai and Bangalore are next-city interest until each is ready.", gain: "Honest waitlists and no fake countdowns", links: [] as { href: string; label: string }[] },
  { phase: "Build context", title: "Profile, Taste and intent — with clear privacy.", body: "Review, profile, Taste and intent help Aynera understand how you like to meet. We explain what is public, what stays private, and what is used only for recommendations.", gain: "Context without a compatibility score", links: [{ href: "/start-with-clarity", label: "Start with clarity" }] },
  { phase: "Discover your way", title: "Duos and/or Squads.", body: "Receive curated introductions, see relevant small gatherings, or both. Squads are an activation of the same local network — not a separate events product.", gain: "More than one way to cross paths", links: [{ href: "/duos", label: "Duos" }, { href: "/squads", label: "Squads" }] },
  { phase: "Meet safely", title: "Talk here first — meet when it feels right.", body: "For Duos, chat in-app and use public-place and date-plan tools. Squad participants follow host and community rules. Safety tools stay free.", gain: "Control before, during, and after the offline step", links: [{ href: "/safety", label: "Explore the Safety centre" }] },
  { phase: "Keep exploring or focus", title: "The network refreshes. Mutual states stay optional.", body: "If nothing clicks, new people and opportunities appear. If one connection does, Focus and Together remain optional mutual states — not a required journey.", gain: "A reason to return without infinite swiping", links: [{ href: "/focus", label: "Focus" }, { href: "/together", label: "Together" }] },
] as const;

export function HowItWorksAtlas() {
  return <main id="main" className="hiw-atlas">
    <section className="hiw-atlas-cover"><div className="shell-x"><p className="pd-eyebrow"><span className="pd-accent-rule" aria-hidden />How it works</p><div className="hiw-atlas-cover-grid"><div><h1 className="pd-mega">Join a local network. Meet in more than one way.</h1></div><p>Not every Aynera session has to end in Focus or Together. You may simply meet new people, exchange contact details, return next week, or leave after finding someone.</p></div><div className="hiw-atlas-principles"><span>No endless feed</span><span>No unilateral relationship mode</span><span>No fake urgency</span></div></div></section>
    <section className="hiw-atlas-gallery" aria-label="How people meet on Aynera"><div className="shell-x"><div><img src="/media/elaris-meet-first.png" alt="Someone arriving to meet in a public place" width={900} height={1100} /><img src="/media/elaris-meet-table.png" alt="Two people talking at a table before deciding to meet again" width={900} height={1100} /><img src="/media/elaris-gatherings-cafe.png" alt="A small group gathering around a shared table" width={900} height={1100} /></div></div></section>
    <section className="hiw-atlas-journey" aria-labelledby="atlas-title"><div className="shell-x hiw-atlas-layout"><aside><p className="pd-eyebrow"><span className="pd-accent-rule" aria-hidden />The use path</p><h2 id="atlas-title" className="pd-display">Five steps through a living local network.</h2><p>Join when there is enough relevant local activity. Discover through Duos and/or Squads. Keep exploring if nothing clicks — Focus and Together stay optional.</p><ol>{steps.map((step, index) => <li key={step.phase}><a href={`#atlas-step-${index + 1}`}><span>{String(index + 1).padStart(2, "0")}</span>{step.phase}</a></li>)}</ol></aside><div className="hiw-atlas-chapters">{steps.map((step, index) => <article key={step.phase} id={`atlas-step-${index + 1}`} className={`hiw-atlas-chapter is-${index + 1}`}><p className="hiw-atlas-chapter-count">{String(index + 1).padStart(2, "0")}</p><p className="hiw-atlas-phase">{step.phase}</p><h3 className="pd-display">{step.title}</h3><p className="hiw-atlas-body">{step.body}</p><div className="hiw-atlas-gain"><span aria-hidden>✦</span><p>You get<br /><b>{step.gain}</b></p></div>{step.links.length > 0 && <div className="hiw-atlas-links">{step.links.map((link) => <Link key={link.href} href={link.href}>{link.label} <span aria-hidden>→</span></Link>)}</div>}</article>)}</div></div></section>
    <section className="hiw-atlas-close"><div className="shell-x"><p className="pd-eyebrow"><span className="pd-accent-rule" aria-hidden />The rule underneath every step</p><h2 className="pd-display">If it isn’t mutual, nothing changes.</h2><p>A request never becomes a relationship state by itself. Focus and Together begin only after both people choose them independently — and either person can still leave respectfully.</p><div><Link href="/early-access" className="pd-cta-warm">Join the founding circle</Link><Link href="/duos">See how Duos works <span aria-hidden>→</span></Link></div></div></section>
  </main>;
}
