import Link from "next/link";

const commitments = [
  { label: "Mutual choice", title: "Two yeses, never one", body: "Exclusivity is a shared decision. Each person confirms independently. Until both say yes, discovery remains available, so no one is placed inside a one-sided commitment." },
  { label: "Shared pause", title: "Discovery ends for both", body: "Once Together begins, introductions, likes, and new matches stop for both people. Success is the moment the product can move out of the relationship’s way." },
  { label: "Freedom remains", title: "A door you can still open", body: "Leaving remains possible. Cooling-off and a respectful close stay available. Together is a commitment chapter, not a cage; honesty matters more than appearances." },
  { label: "What comes next", title: "A private space for two", body: "Together opens the path into Era space—a private corner for the two of you. The search ends so the relationship has room to begin." },
] as const;

export function TogetherOverview() {
  return <main id="main" className="pd-meet-new together-overview">
    <header className="pd-meet-new-hero"><div className="shell-x pd-meet-new-hero-grid"><div className="pd-meet-new-hero-copy"><p className="pd-eyebrow"><span className="pd-accent-rule" aria-hidden />Together</p><h1 className="pd-mega">When you choose each other, we stop the search.</h1><p>Together is the promise made real. Both people confirm exclusivity, and Aynera stops showing either of you anyone else.</p><a href="#inside-together" className="pd-meet-new-jump">See how Together works <span aria-hidden>↓</span></a></div><div className="pd-meet-new-collage together-overview-collage" aria-label="Two moments of building a shared life"><figure className="pd-meet-new-photo pd-meet-new-photo-duo"><img src="/media/elaris-together-us.png" alt="Two people choosing a quiet shared life" width="1200" height="900" /></figure><figure className="pd-meet-new-photo pd-meet-new-photo-squad"><img src="/media/elaris-together-gallery.png" alt="A couple smiling while cooking together at home" width="1200" height="900" /></figure></div></div></header>

    <section id="inside-together" className="together-inside" aria-labelledby="together-title"><div className="shell-x"><div className="together-inside-head"><p className="pd-eyebrow"><span className="pd-accent-rule" aria-hidden />Inside this chapter</p><h2 id="together-title" className="pd-display">Two independent choices.<br />One shared direction.</h2><p>Together does not assume commitment. It begins when two private decisions meet, and it stays respectful even when that direction changes.</p></div><div className="together-convergence"><div className="together-people" aria-hidden><span><i />You</span><span><i />Them</span></div><svg className="together-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden><path d="M0 35 L38 70 M100 35 L62 70" /></svg><span className="together-union" aria-hidden><i /><i /></span><div className="together-commitments">{commitments.map((item, index) => <article key={item.label} className={`is-${index + 1}`}><p>{item.label}</p><h3 className="pd-display">{item.title}</h3><p>{item.body}</p></article>)}</div></div></div></section>

    <section className="pd-meet-new-common together-overview-close"><div className="shell-x"><div className="pd-meet-new-common-head"><p className="pd-eyebrow">What Together means</p><h2 className="pd-display">The search steps back.<br />The relationship steps forward.</h2></div><div className="pd-meet-new-principles"><article><h3>Confirmed by both</h3><p>Together exists only after two independent yeses.</p></article><article><h3>Quiet by design</h3><p>Discovery pauses so attention can stay with the relationship.</p></article><article><h3>Respectful throughout</h3><p>Either person can still choose a different direction with care.</p></article></div><div className="pd-meet-new-common-actions"><Link href="/era-ahead">Explore Era <span aria-hidden>→</span></Link><Link href="/focus">Return to Focus</Link></div></div></section>
  </main>;
}
